# Form implementation generated from reading ui file 'C:\Users\Ayo\Documents\PythonPersonalProjects\Citizenship\ui\citizen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AppointmentFinder(object):
    def setupUi(self, AppointmentFinder):
        AppointmentFinder.setObjectName("AppointmentFinder")
        AppointmentFinder.resize(597, 213)
        self.labelDOB = QtWidgets.QLabel(parent=AppointmentFinder)
        self.labelDOB.setGeometry(QtCore.QRect(10, 20, 161, 16))
        self.labelDOB.setObjectName("labelDOB")
        self.labelEmail = QtWidgets.QLabel(parent=AppointmentFinder)
        self.labelEmail.setGeometry(QtCore.QRect(10, 60, 49, 16))
        self.labelEmail.setObjectName("labelEmail")
        self.entryEmail = QtWidgets.QLineEdit(parent=AppointmentFinder)
        self.entryEmail.setGeometry(QtCore.QRect(170, 60, 401, 21))
        self.entryEmail.setObjectName("entryEmail")
        self.labelFirstname = QtWidgets.QLabel(parent=AppointmentFinder)
        self.labelFirstname.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.labelFirstname.setObjectName("labelFirstname")
        self.entryFirstName = QtWidgets.QLineEdit(parent=AppointmentFinder)
        self.entryFirstName.setGeometry(QtCore.QRect(170, 90, 401, 21))
        self.entryFirstName.setObjectName("entryFirstName")
        self.labelLastName = QtWidgets.QLabel(parent=AppointmentFinder)
        self.labelLastName.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.labelLastName.setObjectName("labelLastName")
        self.entryLastName = QtWidgets.QLineEdit(parent=AppointmentFinder)
        self.entryLastName.setGeometry(QtCore.QRect(170, 120, 401, 21))
        self.entryLastName.setObjectName("entryLastName")
        self.cmdGetCode = QtWidgets.QPushButton(parent=AppointmentFinder)
        self.cmdGetCode.setGeometry(QtCore.QRect(170, 170, 181, 24))
        self.cmdGetCode.setObjectName("cmdGetCode")
        self.cmdExit = QtWidgets.QPushButton(parent=AppointmentFinder)
        self.cmdExit.setGeometry(QtCore.QRect(390, 170, 181, 24))
        self.cmdExit.setObjectName("cmdExit")
        self.cboDays = QtWidgets.QComboBox(parent=AppointmentFinder)
        self.cboDays.setGeometry(QtCore.QRect(170, 20, 81, 31))
        self.cboDays.setObjectName("cboDays")
        self.checkBoxCode = QtWidgets.QCheckBox(parent=AppointmentFinder)
        self.checkBoxCode.setEnabled(True)
        self.checkBoxCode.setGeometry(QtCore.QRect(290, 20, 161, 20))
        self.checkBoxCode.setChecked(True)
        self.checkBoxCode.setObjectName("checkBoxCode")
        self.labelDOB_2 = QtWidgets.QLabel(parent=AppointmentFinder)
        self.labelDOB_2.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.labelDOB_2.setObjectName("labelDOB_2")

        self.retranslateUi(AppointmentFinder)
        QtCore.QMetaObject.connectSlotsByName(AppointmentFinder)

    def retranslateUi(self, AppointmentFinder):
        _translate = QtCore.QCoreApplication.translate
        AppointmentFinder.setWindowTitle(_translate("AppointmentFinder", "Form"))
        self.labelDOB.setText(_translate("AppointmentFinder", "Number of days in the future"))
        self.labelEmail.setText(_translate("AppointmentFinder", "Email:"))
        self.labelFirstname.setText(_translate("AppointmentFinder", "First name:"))
        self.labelLastName.setText(_translate("AppointmentFinder", "Last name:"))
        self.cmdGetCode.setText(_translate("AppointmentFinder", "Check for free appointment"))
        self.cmdExit.setText(_translate("AppointmentFinder", "Exit"))
        self.checkBoxCode.setToolTip(_translate("AppointmentFinder", "If checked, it will proceed with booking the appointment"))
        self.checkBoxCode.setText(_translate("AppointmentFinder", "Book Appointment"))
        self.labelDOB_2.setText(_translate("AppointmentFinder", "to search"))
